# Copyright 2021 The Vitess Authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#    http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

golang_gover: '1.24.5'
golang_hash_linux_amd64:
  '1.18.7': 'sha256:6c967efc22152ce3124fc35cdf50fc686870120c5fd2107234d05d450a6105d8'
  '1.19.3': 'sha256:74b9640724fd4e6bb0ed2a1bc44ae813a03f1e72a4c76253e2d5c015494430ba'
  '1.19.4': 'sha256:c9c08f783325c4cf840a94333159cc937f05f75d36a8b307951d5bd959cf2ab8'
  '1.20.1': 'sha256:000a5b1fca4f75895f78befeb2eecf10bfff3c428597f3f1e69133b63b911b02'
  '1.20.2': 'sha256:4eaea32f59cde4dc635fbc42161031d13e1c780b87097f4b4234cfce671f1768'
  '1.20.3': 'sha256:979694c2c25c735755bf26f4f45e19e64e4811d661dd07b8c010f7a8e18adfca'
  '1.20.4': 'sha256:698ef3243972a51ddb4028e4a1ac63dc6d60821bf18e59a807e051fee0a385bd'
  '1.21.1': 'sha256:b3075ae1ce5dab85f89bc7905d1632de23ca196bd8336afd93fa97434cfa55ae'
  '1.21.3': 'sha256:1241381b2843fae5a9707eec1f8fb2ef94d827990582c7c7c32f5bdfbfd420c8'
  '1.22.0': 'sha256:f6c8a87aa03b92c4b0bf3d558e28ea03006eb29db78917daec5cfb6ec1046265'
  '1.24.5': 'sha256:10ad9e86233e74c0f6590fe5426895de6bf388964210eac34a6d83f38918ecdc'

vitess_git_repo: "https://github.com/vitessio/vitess.git"
vitess_git_version: "main"

mysql_daemon: mysqld

mysql_apt_keyserver: pool.sks-keyservers.net
mysql_apt_key_id: 5072E1F5

mysql_version: 8.0
mysql_repo_rpm: https://dev.mysql.com/get/mysql80-community-release-el8-1.noarch.rpm
mysql_repo_7_rpm: https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
mysql_gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql

mysqld_exporter_binary_local_dir: ""
mysqld_exporter_version: 0.12.1

keyspace: main
vitess_root: '/vt'
clean_vtgate: True
clean_vttablet: True
clean_vtctld: True
vitess_group: vitess
vitess_user: vitess