## Exec Config
exec-type: oltp-set
exec-schema: "./vitess-benchmark/sysbench.json"

## Minimum Vitess version on which the benchmark should be executed
minimum-version: 14

## Ansible
ansible-inventory-file: macrobench_sharded_inventory.yml
ansible-playbook-file: macrobench.yml

## Macrobench cmd
macrobench-sysbench-executable: /usr/local/bin/sysbench
macrobench-workload-path: oltp_read_write_with_settings
macrobench-skip-steps:
macrobench-type: oltp-set

## Sysbench all steps
macrobench_all_mysql-db: main
macrobench_all_mysql-host: 127.0.0.1
macrobench_all_mysql-port: 13306
macrobench_all_db-ps-mode: disable
macrobench_all_db-driver: mysql
macrobench_all_luajit-cmd: "off"
macrobench_all_threads: 42
macrobench_all_auto-inc: "off"
macrobench_all_tables: 10
macrobench_all_table_size: 10000
macrobench_all_rand-type: uniform
macrobench_all_rand-seed: 1

## Sysbench prepare step
macrobench_prepare_time: 60
macrobench_prepare_report-interval: 10

## Sysbench run step
macrobench_run_time: 600
macrobench_run_report_json: true
macrobench_run_verbosity: 0
macrobench_run_warmup-time: 120

# Vitess Extra Flags
exec-vitess-config:
  15: # will match >= v15.0.0 and override the flags defined in < 15.0.0
    vttablet: --queryserver-enable-settings-pool=true
