## Exec configuration
exec-type: tpcc_fk
exec-schema: "./vitess-benchmark/tpcc_fk_vschema.json"
minimum-version: 18

## Ansible
ansible-inventory-file: macrobench_unsharded_inventory.yml
ansible-playbook-file: macrobench.yml

## Macrobench cmd
macrobench-sysbench-executable: /usr/local/bin/sysbench
macrobench-workload-path: /src/sysbench-tpcc/tpcc.lua
macrobench-skip-steps:
macrobench-type: tpcc_fk
macrobench-working-directory: /src/sysbench-tpcc

## Sysbench all steps
macrobench_all_mysql-db: main
macrobench_all_mysql-host: 127.0.0.1
macrobench_all_mysql-port: 13306
macrobench_all_db-ps-mode: disable
macrobench_all_db-driver: mysql
macrobench_all_luajit-cmd: "off"
macrobench_all_threads: 42
macrobench_all_tables: 1
macrobench_all_scale: 50
macrobench_all_rand-type: uniform
macrobench_all_rand-seed: 1
macrobench_all_use_fk: 1
macrobench_all_mysql-ignore-errors: all

## Sysbench prepare step
macrobench_prepare_time: 60
macrobench_prepare_report-interval: 10

## Sysbench run step
macrobench_run_time: 600
macrobench_run_report_json: "yes"
macrobench_run_verbosity: 0
macrobench_run_warmup-time: 120